@baseUrl = https://localhost:7115
@pacientesUrl = {{baseUrl}}/api/pacientes

# @name login
POST {{baseUrl}}/login?useCookies=false
Content-Type: application/json

{
  "email": "carles2@ejemplo.com",
  "password": "aA123456!"
}

###

GET {{pacientesUrl}}/019D29FF-F17F-7061-9F66-6CDD8106A363
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

###

GET {{pacientesUrl}}
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

###

POST {{pacientesUrl}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

{
  "nombre": "Paciente 1",
  "email": "paciente1@example.com"
}
